---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: capoa-controlplane-system
spec:
  selector:
    control-plane: capoa-controlplane-controller-manager
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443

